project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo, Email


class LoginForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])


class RegisterForm(FlaskForm):
    name = StringField(
        'Name',
        validators=[DataRequired(), Length(min=2, max=64)])

    surname = StringField(
        'Surname',
        validators=[DataRequired(), Length(min=2, max=64)])

    email = StringField(
        'email',
        validators=[DataRequired(), Email(message=None), Length(min=6, max=40)])

    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=6, max=25)])

    confirm = PasswordField(
        'Repeat password',
        validators=[DataRequired(), EqualTo('password', message='Passwords must match.')])

project/users/views.py
from flask import flash, redirect, render_template, url_for, request, Blueprint
from project.users.forms import LoginForm, RegisterForm
from project.models import User, bcrypt
from project import db
from flask_login import login_user, login_required, logout_user, current_user
from project.token import generate_verification_token, verify_token
from project.email import send_email
from sqlalchemy import exc  # exceptions


users_blueprint = Blueprint('users', __name__, template_folder='templates')


# login page
@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    error = None
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(username=request.form['username']).first()
            if user is not None and bcrypt.check_password_hash(user.password, request.form['password']):
                # session['logged_in'] = True
                login_user(user)  # (flask_login) session created
                flash('You are logged in.')
                return redirect(url_for('home.home'))
            else:
                error = 'Invalid Credentials. Please try again.'
    return render_template('login.html', form=form, error=error)


@users_blueprint.route('/logout')
@login_required  # flask_login
def logout():
    logout_user()  # (flask_login) clear session
    flash('You are logged out.')
    return redirect(url_for('home.welcome'))


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            name=form.name.data,
            surname=form.surname.data,
            email=form.email.data,
            username=form.email.data.split("@")[0],
            password=form.password.data,
            verified=False
        )
        db.session.add(user)
        try:
            db.session.commit()
        except exc.IntegrityError:
            flash("User already exists!", "error")
            return render_template('register.html', form=form)

        token = generate_verification_token(user.email)

        verification_url = url_for('users.verify_email', token=token, _external=True)
        html = render_template('activate.html', verification_url=verification_url)
        subject = "Please verify your email"
        send_email(user.email, subject, html)

        login_user(user)
        flash("Verification link has been sent via email", "success")

        return redirect(url_for('users.unverified'))

    return render_template('register.html', form=form)


@users_blueprint.route('/verify/<token>')
@login_required
def verify_email(token):
    try:
        email = verify_token(token)
        user = User.query.filter_by(email=email).first_or_404()
    except:
        flash('Verification link is invalid or has expired.', 'danger')
        return redirect(url_for('home.home'))

    if user.verified:
        flash('Account already verified. Please login.', 'success')
    else:
        user.verified = True
        db.session.add(user)
        db.session.commit()
        flash('You have verified your account. Thanks!', 'success')
    return redirect(url_for('home.home'))


@users_blueprint.route('/unverified')
@login_required
def unverified():
    if current_user.verified:
        return redirect(url_for('home.home'))
    flash('Please verify your account!', 'warning')
    return render_template('unverified.html')


@users_blueprint.route('/resend')
@login_required
def resend_verification():
    token = generate_verification_token(current_user.email)
    verification_url = url_for('users.verify_email', token=token, _external=True)
    html = render_template('activate.html', verification_url=verification_url)
    subject = "Please verify your email"
    send_email(current_user.email, subject, html)
    flash('A new verification email has been sent.', 'success')
    return redirect(url_for('users.unverified'))

project/users/templates/activate.html
<p>Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ verification_url }}">{{ verification_url }}</a></p>

project/users/templates/login.html
{% extends "base.html" %}

{% block custom_head %}
<title>Login</title>
    <!-- Custom styles for this template -->
    <link href="./static/login.css" rel="stylesheet">

{% endblock %}

{% block content %}
    <form class="form-signin" action="" method="post">
  <img class="mb-4" src="./static/logo.jpg" alt="" width="204" height="60">
  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

  {{ form.csrf_token }}

  <p>
        {{ form.username(autocomplete="off", class_="form-control", autofocus="true", placeholder="Username") }}
    <span class="error">

      {% if form.username.errors %}
        {% for error in form.username.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}

    </span>
  </p>

  <p>

  {{ form.password(autocomplete="off", class_="form-control", placeholder="Password") }}


    <span class="error">
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>

  </p>

  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>

{% endblock %}

project/users/templates/register.html
{% extends "base.html" %}

{% block custom_head %}
<title>Register</title>
    <!-- Custom styles for this template -->
    <link href="./static/login.css" rel="stylesheet">

{% endblock %}

{% block content %}

<h1>Please Register</h1>
<br>
<form class="form-signin" role="form" method="post" action="">
  {{ form.csrf_token }}
  <p>
    {{ form.name(autocomplete="off", class_="form-control", placeholder="Name") }}
    <span class="error">
      {% if form.name.errors %}
        {% for error in form.name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
    {{ form.surname(autocomplete="off", class_="form-control", placeholder="Surname") }}
    <span class="error">
      {% if form.surname.errors %}
        {% for error in form.surname.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.email(autocomplete="off", class_="form-control", placeholder="email") }}
    <span class="error">
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.password(autocomplete="off", class_="form-control", placeholder="password") }}
    <span class="error">
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.confirm(autocomplete="off", class_="form-control", placeholder="confirm") }}
    <span class="error">
      {% if form.confirm.errors %}
        {% for error in form.confirm.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button class="btn btn-lg btn-success btn-block" type="submit">Register!</button>
</form>

{% endblock %}

project/users/templates/unverified.html
{% extends "base.html" %}

{% block content %}

<h1>Welcome!</h1>
<br>
<p>You have not verified your account. Please check your inbox (and your spam folder) -
    you should have received an email with a verification link.</p>
<p>Didn't get the email? <a href="{{ url_for('users.resend_verification') }}">Resend</a>.</p>

{% endblock %}